/**
 * Maps character dialogue lines to pre-recorded audio file paths.
 * Audio files are generated by scripts/generate-voices.mjs using ElevenLabs.
 *
 * Files live in: public/audio/voices/{characterId}/{category}_{index}.mp3
 *
 * Lines with dynamic placeholders ({min}, {max}, {nearAnswer}) don't have
 * pre-recorded audio and fall back to Web Speech API (TTS).
 */

// ────────────────────────────────────────────
// Types
// ────────────────────────────────────────────

export interface VoiceAudioInfo {
  /** Path relative to public root, e.g. "/audio/voices/pascual/greeting_0.mp3" */
  audioPath: string | null;
  /** Whether this line has dynamic placeholders (no pre-recorded audio) */
  isDynamic: boolean;
}

// ────────────────────────────────────────────
// Categories that have template placeholders
// (these lines can't be pre-generated)
// ────────────────────────────────────────────

const DYNAMIC_CATEGORY = 'hint4';

// ────────────────────────────────────────────
// Lookup function
// ────────────────────────────────────────────

/**
 * Get the audio file path for a dialogue line.
 *
 * @param characterId - Character key (e.g. "pascual", "berta-bruno")
 * @param category    - Dialogue category (e.g. "greeting", "correct")
 * @param lineIndex   - Index of the line within the category array
 * @returns Audio info with path (or null if dynamic/not available)
 */
export function getVoiceAudioPath(
  characterId: string,
  category: string,
  lineIndex: number,
): VoiceAudioInfo {
  // hint4 lines have placeholders — no pre-recorded audio
  if (category === DYNAMIC_CATEGORY) {
    return { audioPath: null, isDynamic: true };
  }

  return {
    audioPath: `/audio/voices/${characterId}/${category}_${lineIndex}.mp3`,
    isDynamic: false,
  };
}

/**
 * Check if a manifest file exists and load it for validation.
 * In production, we just construct paths deterministically.
 * The manifest is only used by the generation script.
 */

// ────────────────────────────────────────────
// Alicia's voice audio paths
// ────────────────────────────────────────────

/**
 * Get audio path for Alicia's own voice lines.
 * Alicia's categories differ from animal characters.
 */
export function getAliciaAudioPath(
  category: string,
  lineIndex: number,
): VoiceAudioInfo {
  return {
    audioPath: `/audio/voices/alicia/${category}_${lineIndex}.mp3`,
    isDynamic: false,
  };
}
